"""Cancel-intent message templates (spec 5.3).

Deliberately messy: Hinglish, lowercase, typos, no punctuation. Free text is
one of the reasons this problem is not a lookup table.
"""
from __future__ import annotations

TEMPORARY = [
    "travelling for 2 months, dont charge me pls",
    "salary late this month, can I skip?",
    "paused kar do next month tak",
    "going abroad in september, stop billing till nov",
    "can i skip this month only",
    "money is tight right now, can we pause",
    "hospital expenses this month, please hold the payment",
    "shifting cities, need a break for a few weeks",
    "please dont debit this month, will resume later",
    "temporarily stop, i will come back",
    "exams going on, wont use for 2 months",
    "can you hold my subscription for 30 days",
    "abhi paisa nahi hai, next month se start karo",
    "need to pause, cash flow issue",
    "on maternity leave, pause for now",
    "wont be using it in october, skip that cycle",
    "please freeze my account for a month",
    "my salary date changed, can you charge later",
    "just this once, skip the payment",
    "family emergency, pause billing please",
    "travelling to my hometown, hold it",
    "can we defer this month payment",
    "kuch time ke liye band kar do",
    "job change ho raha hai, 1 month pause chahiye",
    "please stop auto debit temporarily not permanently",
    "i want to pause not cancel",
    "hold the plan for 6 weeks please",
    "moving house this month, pause it",
    "internet not working at new place, pause till i shift",
    "will be out of country, resume in december",
    "short on funds till 5th, charge after that",
    "please skip october billing",
    "medical leave, need a break from payments",
    "can i pause instead of cancelling",
    "bas ek mahina rok do",
    "not using this month due to travel",
    "please pause, dont cancel my account",
    "temporary hold required for 45 days",
    "wedding expenses, pause for 2 cycles",
    "account balance low till salary, please wait",
    "i will be away, freeze my plan",
    "need a payment holiday this month",
]

PRICE = [
    "too expensive now",
    "found cheaper option",
    "price is too high for me",
    "cant afford this plan anymore",
    "do you have a cheaper plan",
    "competitor is giving half the price",
    "reduce the price or i will cancel",
    "this is costing me too much monthly",
    "bahut mehenga hai, koi sasta plan hai",
    "want to downgrade to basic",
    "the premium plan is not worth it",
    "can i move to a smaller plan",
    "price increased without telling me, cancel",
    "budget cut, need a lower tier",
    "999 is too much, do you have 499",
    "not getting value for this price",
    "switching to a cheaper service",
    "downgrade my plan please",
    "too costly, cancel it",
    "i only need basic features, why pay full",
    "monthly charge is high, any discount",
    "plan is overpriced for what i use",
    "give me a discount or i leave",
    "cheaper alternative available, cancelling",
    "cost cutting at work, need to reduce",
    "can you lower the amount",
    "paisa zyada lag raha hai",
    "i want the cheapest plan you have",
    "not worth 1499 per month",
    "reduce my subscription amount",
    "moving to the free tier",
    "price hike is unacceptable, cancel",
    "any student discount available",
    "too pricey, downgrade or cancel",
    "want same service for less money",
    "the annual plan is cheaper, switch me",
    "cant justify this expense",
    "looking for something more affordable",
    "half the price elsewhere, why should i stay",
    "reduce cost please otherwise stop",
]

DONE = [
    "not using anymore, cancel",
    "course finished",
    "please cancel my subscription permanently",
    "dont need this service now",
    "project is over, stop billing",
    "cancel it, i am done",
    "we have moved to another vendor",
    "no longer required, close my account",
    "completed my training, cancel",
    "stop the subscription, not interested",
    "band kar do, ab zarurat nahi",
    "i have finished what i needed",
    "shutting down my business, cancel",
    "unsubscribe me permanently",
    "not useful for me, please cancel",
    "cancel and delete my account",
    "we built our own solution, cancelling",
    "my child finished the course, stop it",
    "no longer in this line of work",
    "please terminate the plan",
    "done with the service, thank you",
    "cancel from next month permanently",
    "i dont want it anymore",
    "close the subscription for good",
    "retired, dont need it",
    "team disbanded, cancel all seats",
    "finished the syllabus, cancel",
    "stop charging me, i quit",
    "permanently cancel, not a pause",
    "we are not renewing this",
    "service no longer relevant to us",
    "please cancel, i wont be coming back",
    "hamesha ke liye band karo",
    "cancel my plan, moving on",
    "the need is over, end it",
    "wrap up my subscription please",
    "i am closing this account",
    "not required going forward",
    "please discontinue my membership",
    "end the subscription now",
]

BY_CLASS = {"temporary": TEMPORARY, "price": PRICE, "done": DONE}
